### ISSUE TITLE
FMI export support

### ISSUE THREAD

**Issue by traversaro** [SFI-Mechatronics/FMI4cpp#2]
Hi @markaren, 
    thanks for the great work on the library! 

I had a small question,  as I was not able to find this info in the README. At the moment the library provides support for importing FMUs, but I was  wondering if you have planned/are interested  in providing facilities/support for implementing FMU in C++, in a sense providing support for  "FMI export".

**Comment by markaren** [comment]
I have not laid any plans for it, but it could be a possibility in the future. However, I doubt I will do anything it in the near future.

**Comment by traversaro** [comment]
Ok, thanks for the info. Closing, if someone is interested in implementing this feature a new issue can be opened.
