### ISSUE TITLE
lower c++ standard requirement ?

### ISSUE THREAD

**Issue by jschueller** [SFI-Mechatronics/FMI4cpp#21]
Hi,
I noticed the library requires cxx17, what is that you actually require ? (I did not spot anything fancy in the code).

**Comment by markaren** [comment]
I use std::optional and std::filesystem and c++17 namespaces. Is there a particular reason why you would want the requirement to be lowered?

**Comment by jschueller** [comment]
Yes, I'd need to build with older compilers (gcc5 for example).

**Comment by markaren** [comment]
It is entirely possible to lower the requirements by using boost::optional, boost::filesystem ( I used this in the very start) and non-nested namespaces. However, I am a bit reluctant to do so. But if it turns out to be a problem for adoption, I might have to reconsider..

**Comment by markaren** [comment]
But if you really want this to happen, one solution could be to use non-nested namespaces and additionally introduce have a CMake option that defines a macro that defines whether or not we should use std or boost versions of optional and filesystem. This I could live with. Is c++14 ok?

I could do this myself, but it would not happen overnight. A pull request would be preferable.
