### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by markaren** [SFI-Mechatronics/FMI4cpp#28]
Logging is clumsy and should be improved.

Today it's like this:

```
#if FMI4CPP_DEBUG_LOGGING_ENABLED
    cout << "Hello world!'" << endl;
#endif
```

```FMI4CPP_DEBUG_LOGGING_ENABLED``` can be misspelled and the message is only printed in debug mode and cannot be turned off. A logging framework provided more control should probably be used.

There are probably some best practices in the C++ that should be followed?

**Comment by traversaro** [comment]
I heard good thing in the past about https://github.com/gabime/spdlog , but I actually never used it.

**Comment by markaren** [comment]
@traversaro Will consider it. Thanks!
