### ISSUE TITLE
Add port to vcpkg

### ISSUE THREAD

**Issue by markaren** [SFI-Mechatronics/FMI4cpp#4]
Add [vcpkg](https://github.com/Microsoft/vcpkg) port. Should be straight forward, but I want to wait a little while to allow the API to settle.

**Comment by markaren** [comment]
@traversaro I'm testing a fmi4cpp port as we speak. Seems to work!
Thanks you for the work on the install target!

**Comment by markaren** [comment]
One issue though.

I do the following some places in the code:

```cpp
#ifndef NDEBUG
    cout << "this only prints in debug mode" << endl;
#endif
```
which works as expected when developing fmi4cpp, but when I integrated fmi4cpp in an external project using vcpkg, the messages prints regardless of mode.. How to fix?

**Comment by traversaro** [comment]
That is strange, it seems that for some reason the Debug version of fmi4cpp is linked also for Release builds. I guess you are missing a call to `vcpkg_fixup_cmake_targets`, see https://github.com/Microsoft/vcpkg/issues/1183 and  https://github.com/Microsoft/vcpkg/issues/77 .

Not directly related to this, but I guess it would also be beneficial to have different names  for Release and Debug libraries when compile in Visual Studio, this is typically implemented adding:
~~~
if(MSVC)
    set(CMAKE_DEBUG_POSTFIX "d")
endif()
~~~
See https://github.com/robotology/how-to-export-cpp-library/blob/master/CMakeLists.txt#L50 for more info.

**Comment by traversaro** [comment]
Additional comment: it would be good if the version in vcpkg was consistent with the version listed in CMake files https://github.com/SFI-Mechatronics/FMI4cpp/blob/master/CMakeLists.txt#L10 .

**Comment by markaren** [comment]
The idea is to get the port working locally, then make a release. The port should then be updated to use the zipped archive from github rather than a commit hash. Then the port will be versioned similar to the release.

**Comment by markaren** [comment]
I guess this is what you talked about earlier w.rt. CMake project name and vcpkg, because FMI4cpp folder exists, but not fmi4cpp

**Comment by markaren** [comment]
Renamed CMake project so that ```vcpkg_fixup_cmake_targets()``` succeeds, but same issue w.r.t debug messages during release configuration.

**Comment by markaren** [comment]
Another thing @traversaro , when NOT applying ```vcpkg_fixup_cmake_targets()``` I don't have to link libzip++ in the target application. Why does this change with the command applied?

**Comment by traversaro** [comment]
I am not sure, but I suspect that is related to the non-relocatable nature of some parts of the CMake configuration files that I was mentioned in the PR comments.

**Comment by markaren** [comment]
@traversaro , the debug issue has nothing to do with  vcpkg. Tested it using cmake/make on the command line and running the generated example executables. ```-DCMAKE_BUILD_TYPE=Release``` needs to be passed to CMake..

**Comment by markaren** [comment]
> I guess this is what you talked about earlier w.r.t. CMake project name and vcpkg, because FMI4cpp folder exists, but not fmi4cpp.

Can be resolved by specifying the path manually:
vcpkg_fixup_cmake_targets(CONFIG_PATH "share/FMI4cpp" TARGET_PATH "share/FMI4cpp")

**Comment by markaren** [comment]
By NOT including ```target_link_libraries(...)``` this port behaves just as I want. The only thing the client application needs to do in order to have run fmi4cpp is to:
```target_link_libraries(main PRIVATE FMI4cpp::fmi4cpp)```

With the fixup command, the client application needs to link all 3rd party dependencies manually.

Not sure which is the correct thing to do..

**Comment by traversaro** [comment]
Have you tested this on Linux or Windows? I am afraid I will not have time to check this before the weekend.

**Comment by markaren** [comment]
Ubuntu 18.04. Will try Windows soon

**Comment by markaren** [comment]
Windows:
_without_: ```vcpkg_fixup_cmake_targets``` fails due to
```
Import libs were not present in C:\Users\laht\AppData\Local\vcpkg\packages\fmi4cpp_x86-windows\debug\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
Import libs were not present in C:\Users\laht\AppData\Local\vcpkg\packages\fmi4cpp_x86-windows\lib
If this is intended, add the following line in the portfile:
    SET(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
The following DLLs have no exports:

    C:/Users/laht/AppData/Local/vcpkg/packages/fmi4cpp_x86-windows/debug/bin/fmi4cppd.dll
    C:/Users/laht/AppData/Local/vcpkg/packages/fmi4cpp_x86-windows/bin/fmi4cpp.dll

DLLs without any exports are likely a bug in the build script.
There should be no empty directories in C:/Users/laht/AppData/Local/vcpkg/packages/fmi4cpp_x86-windows
The following empty directories were found:

    C:/Users/laht/AppData/Local/vcpkg/packages/fmi4cpp_x86-windows/lib
    C:/Users/laht/AppData/Local/vcpkg/packages/fmi4cpp_x86-windows/debug/lib

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)
```

_with_: fails due to empty packages/*/share folder (these are populated on Ubuntu)

**Comment by markaren** [comment]
I have managed to get everything working, except I'm facing two issues

1) After installation vcpkg prints
```
find_package(FMI4cpp CONFIG REQUIRED)
target_link_libraries(main PRIVATE LIBZIP::LIBZIP FMI4cpp::FMI4cpp)
```
even though 
```
target_link_libraries(main PRIVATE LIBZIP::LIBZIP FMI4cpp::FMI4cpp)
```
would suffice. This is a minor issue

2. Windows clients will run into the foollowing error:
```
error C2872: 'byte': ambiguous symbol
```
as discussed here: https://developercommunity.visualstudio.com/content/problem/93889/error-c2872-byte-ambiguous-symbol.html 

I believe the issue is due to one of the 3rd party dependencies, as I do not define byte.
This would not happen if we targeted C++14. Perhaps that's the easiest fix...

**Comment by markaren** [comment]
Ok, finally think I got it! Will try to make a pull request tomorrow with the required changes. 
Perhaps I'll file a pull request with vcpkg already in the weekend.

**Comment by markaren** [comment]
Should be ok to publish a vcpkg port now. Will make a release and use that as the vcpkg source.

**Comment by markaren** [comment]
Work on this issue has been postpones while some heavy refactoring of the code is being done. A port will not be published before FMI4cpp has been successfully integrated into FMU-proxy (see https://github.com/SFI-Mechatronics/FMU-proxy/issues/58 )
