### ISSUE TITLE
Add an install target

### ISSUE THREAD

**Issue by traversaro** [SFI-Mechatronics/FMI4cpp#8]
For using the library in a external projects, it is convenient to add an `install` target using the CMake's [`install` command](https://cmake.org/cmake/help/v3.12/command/install.html) to install library files, header files and CMake exported targets and configuration files (see https://cmake.org/cmake/help/v3.12/manual/cmake-packages.7.html and https://github.com/robotology/how-to-export-cpp-library). 

Do you plan to add those? I would be happy to help on this, if you need any support.

**Comment by markaren** [comment]
Yes, probably this is something required for #4 as well. I would love to see a pull request on this. I only started with C++ and CMake this summer, so I welcome all the help/suggestions I can get.

**Comment by markaren** [comment]
Initial prototype has been merged through #15 . Further work can be discussed in separate issues
